services:
  - name: customer-service
    image: mohammedamrath/customerservice
    repository:
      image: mohammedamrath/customerservice
      tag: latest
    port: 3001
    replicas: 2
    namespace: tomato
  - name: order-service
    image: mohammedamrath/orderservice
    repository:
      image: mohammedamrath/orderservice
      tag: latest
    port: 3002
    replicas: 1
    namespace: tomato
